version: '3'

services:
  trivy:
    image: aquasec/trivy
    command: ["--auto-refresh", "--cache-dir", "/var/cache/trivy"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/cache/trivy


  # owasp-zap:
  #   image: owasp/zap2docker-stable
  #   command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8080", "-config", "api.disablekey=true"]
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - scan-network

  # sonarqube:
  #   image: sonarqube
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - scan-network

  # dependency-check:
  #   image: owasp/dependency-check:latest
  #   command: ["--project", "my-project", "--scan", "/app"]
  #   volumes:
  #     - .:/app
  #     - dependency-check-data:/usr/share/dependency-check/data
  #   networks:
  #     - scan-network
